apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-seagate
  labels:
    type: local
spec:
  storageClassName: seagate-driver
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.26
    path: /mnt/k8s-volume
