apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus
  namespace: metrics
  labels:
    app: prometheus
    purpose: metrics

spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
      purpose: metrics
  template:
    metadata:
      labels:
        app: prometheus
        purpose: metrics
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml

          - name: prometheus-alert-etcd
            mountPath: /etc/alerts/etcd.alerts.yml
            subPath: etcd.alerts.yml

          - name: prometheus-alert-test
            mountPath: /etc/alerts/test.alerts.yml
            subPath: test.alerts.yml

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-alert-etcd
          configMap:
            name: prometheus-alert-etcd
        - name: prometheus-alert-test
          configMap:
            name: prometheus-alert-test
