kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: metrics
spec:
  selector:
    app: prometheus
    purpose: metrics
  ports:
  - port: 9090
    targetPort: 9090
  type: LoadBalancer
