apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-volume-claim-nginx
  namespace: examples
  labels:
    app: private-volume-claim-nginx
    purpose: examples
spec:
  selector:
    matchLabels:
      app: private-volume-claim-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: private-volume-claim-nginx
        purpose: examples
    spec:
      containers:
      - image: nginx
        name: private-volume-claim-nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs-seagate
