kind: Service
apiVersion: v1
metadata:
  name: private-volume-claim-nginx
  namespace: examples
spec:
  selector:
    app: private-volume-claim-nginx
    purpose: examples
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
