apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - persistent-volume-claim
  - metrics-redis

resources:
  - namespace.yml
  - persistentVolume.yml
  - persistentVolumeClaim.yml
