apiVersion: v1
kind: PersistentVolume
metadata:
  name: exmaples-pv
  labels:
    type: local
spec:
  storageClassName: examples-storage
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.26
    path: /mnt/k8s-volume/examples
