apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: examples-pvc
  namespace: examples
spec:
  storageClassName: examples-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
