- hosts: master
  remote_user: ubuntu
  gather_facts: false

  tasks:
    # Have your hosts ready before running this command
    - name: Add Hosts
      register: ps
      script: ../scripts/hosts.sh
    - debug: var=ps.stdout_lines

    - name: Disable Swap
      register: ps
      script: ../scripts/swap.sh
    - debug: var=ps.stdout_lines

    - name: Install Docker
      register: ps
      script: ../scripts/docker.sh
    - debug: var=ps.stdout_lines

    - name: Install Kubernetes
      register: ps
      script: ../scripts/kubernetes.sh
    - debug: var=ps.stdout_lines

    - name: Update Packages
      register: ps
      script: ../scripts/update.sh
    - debug: var=ps.stdout_lines

    - name: Instal kubeadm
      register: ps
      script: ../scripts/kubeadm.sh
    - debug: var=ps.stdout_lines

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "[OS] REBOOTING"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
    - debug: var=ps.stdout_lines
