kind: Service
apiVersion: v1

metadata:
  name: prometheus-alerts
  namespace: metrics

spec:
  selector:
    app: prometheus-alerts
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
