apiVersion: apps/v1
kind: Deployment

metadata:
  name: kube-state-metrics
  namespace: metrics
  labels:
    app: kube-state-metrics
    purpose: metrics

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
      purpose: metrics
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
        purpose: metrics
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/version: 1.9.3
    spec:
      containers:
        - name: kube-state-metrics
          image: rhuss/kube-state-metrics:v1.9.3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http-metrics
            - containerPort: 8081
              name: telemetry
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
          securityContext:
            runAsUser: 65534
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      serviceAccountName: kube-state-metrics
