apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - metrics-server
  - kube-state-metrics
  - node-exporter
  - prometheus
  - prometheus-alerts
  - grafana

resources:
  - namespace.yml
